### ISSUE TITLE
Possible new feature?

### ISSUE THREAD

**Issue by lifeiscontent** [krasimir/absurd#111]
I'm not sure if there is already a feature to do this, but I think this would be incredibly powerful.

I was about to write my own JS to CSS engine for this 1 feature.

having something like this

app/css/components/BareList.js
``` js
var api = Absurd();
var BareList = api.add({
  margin: '0',
  padding: '0',
  listStyle: 'none'
});

module.exports = {
  block: BareList
};
```

app/css/components/HorizonalList.js
``` js
var api = Absurd();
var BareList = require('../css/components/BareList').block;
var HorizonalList = api.extends(BareList);

var HorizontalListItem = api.add({
  display: 'inline-block'
});

module.exports = {
  block: HorizontalList,
  item: HorizontalListItem
};
```

basically using the require system to do dependency checking and optimizing for a smaller CSS file.

**Comment by krasimir** [comment]
Hi @lifeiscontent 

first of all, sorry for not responding to your question. I don't think that you need something special to use the `require` system together with AbsurdJS. What matters for this library is to pass a object to the `compile` method. So you could have:

app/css/components/BareList.js
```js
var BareList = {
  margin: '0',
  padding: '0',
  listStyle: 'none'
};
module.exports = {
  block: BareList
};
```
app/css/components/HorizonalList.js
```js
var api = Absurd();
var extend = require('extend')
var BareList = require('../css/components/BareList').block;
var HorizonalList = extend({
  fz: '1.2em'
}, BareList);

var HorizontalListItem = {
  display: 'inline-block'
};

module.exports = {
  block: HorizontalList,
  item: HorizontalListItem
};
```
I used https://www.npmjs.com/package/extend here but you may fetch another similar tool. Let me know if that makes sense.

**Comment by lifeiscontent** [comment]
@krasimir you expose the api variable but never use it, why?

**Comment by krasimir** [comment]
Well, it is not true that I'm not using it. In your example it is not needed. In general I prefer to keep the library as simple as possible. If there is something that could be done easily outside AbsurdJS then we better do it there.
