### ISSUE TITLE
Use component as standalone class

### ISSUE THREAD

**Issue by clemorphy** [krasimir/absurd#116]
Hi !

Would there be any problem in using a component (I'm thinking about the Router component) as a standalone class ?
Does this specific component rely on other parts of the library ?

Thanx.

**Comment by krasimir** [comment]
I don't think that there will be a problem. I had this in mind. I mean I wanted to develop the different parts as little independent libraries. I'm not sure what exactly you want to achieve thought. Try and let me know if something goes wrong. I would love to help.

**Comment by clemorphy** [comment]
Actually I am not interested in the server side part of the library. I was looking for a JS script to handle the routing of a single page site, with a small footprint, and your Router component seems to provide what I need (routes handling, pushstate support with hash fallback).

**Comment by krasimir** [comment]
Oh then I'll suggest to check this article http://krasimirtsonev.com/blog/article/A-modern-JavaScript-router-in-100-lines-history-api-pushState-hash-url It is basically the same JavaScript component used in AbsurdJS.

**Comment by clemorphy** [comment]
I have read your article but I was worried about the freshness of the code compared to the component version on github, especially because of the line `window.location.href.match(/#(.*)$/);` which seems to be useless, like exposed in the comments. But I can see this line is identical in the github version.

Should I use the github version, or the one in your article ?

**Comment by krasimir** [comment]
Definitely the GitHub version.

**Comment by krasimir** [comment]
@clemorphy I'm closing this one. Let me know if you have any other questions and I'll reopen it. Thanks.
