### ISSUE TITLE
add reference to `jstransformer-absurd`

### ISSUE THREAD

**Issue by tunnckoCore** [krasimir/absurd#120]
wazzup!

You can add https://github.com/jstransformers/jstransformer-absurd to the readme. Or if you want I can PR :)

**Comment by tunnckoCore** [comment]
it looks lil bit hacky but yea.. because the absurd's not so node-friendly api.

**Comment by tunnckoCore** [comment]
It use `postcss` to transform nested css to valid css then pass it to importCSS method if filepath to css file given.

**Comment by krasimir** [comment]
@tunnckoCore looks good to me. Can you please prepare a PR and I'll merge it into master.

**Comment by tunnckoCore** [comment]
@krasimir Im not sure where to add it. :)

Така де, хаха.

**Comment by krasimir** [comment]
Готово :)

**Comment by tunnckoCore** [comment]
Looks good, cool :+1:
