### ISSUE TITLE
fz = font-size? that's absurd

### ISSUE THREAD

**Issue by offthegrass** [krasimir/absurd#121]
what was the thinking behind this? surely it should be `fs`, or if there's a clash, even `fsz` would make more sense. 

p.s. really useful package, thanks!

**Comment by tunnckoCore** [comment]
:+1: yea I also notice this, before few days

**Comment by krasimir** [comment]
Hello @offthegrass and @tunnckoCore 

There was a clash with Node.js's native module `fs`. I really can't remember where that was and to be honest right now I'm can't even come with a case where this is possible.

**Comment by offthegrass** [comment]
@krasimir are you sure? looks like ` fs ` is [font-style](http://absurdjs.com/pages/css-preprocessing/organic-css/atoms/). 

it's actually not a huge deal, I don't think it's worth changing given the number of people it would inconvenience.
