### ISSUE TITLE
How to prevent closing attributes?

### ISSUE THREAD

**Issue by IonicaBizau** [krasimir/absurd#125]
So, if I have `{ "img.foo[src='bar']": "" }`, Absurd generates for me:

```html
<img class="foo" src='bar'></img>
```

How to prevent the `</img>` tag? I don't want it there.

----

Thanks, @krasimir for awesome project! I'm gonna use it in a project. Best regards from Romania. :smile:

**Comment by krasimir** [comment]
To prevent the the closing tag use `null` instead of `""` as a property value:

```js
{ "img.foo[src='bar']": null }
```

jsbin [here](http://jsbin.com/tojupopaje/1/edit?js,output).

**Comment by IonicaBizau** [comment]
Ha, awesome and fast! Thaaanks! :cake:

**Comment by krasimir** [comment]
You are welcome :)

**Comment by IonicaBizau** [comment]
@krasimir You just got a shiny :star2: from me. :dizzy:

**Comment by krasimir** [comment]
:)
